seeder:
  file: ./seeder/seeder.rb
  disabled: false
  
parsers: 
  - file: ./parsers/search.rb
    page_type: search
    deisabled: false

  - file: ./parsers/product.rb
    page_type: product
    disabled: true